### ISSUE TITLE
Use Brreg in controller

### ISSUE THREAD

**Issue by ronnyandre** [HelgeSverre/Brreg#1]
Is it possible to use this in a controller?

**Comment by kentdahl** [comment]
This seems to work for me both in controller and tinker command line on Laravel 5.7:

```PHP
# Include the class.
use HelgeSverre\Brreg\BrregService;

# In a controller method.
$brreg = app()->make(BrregService::class);
$data = $brreg->getCompanyData('996888460');
```

Might be a better way to instantiate the service, but I'm not too familiar with the service container injection magic.

**Comment by ronnyandre** [comment]
Great, thanks!
