### ISSUE TITLE
How to run the unit tests?

### ISSUE THREAD

**Issue by kentdahl** [HelgeSverre/Brreg#3]
I'm running a blank on how to run the unit tests. The regular install and run `phpunit` steps failed me. 

```
composer require --dev phpunit/phpunit
vendor/bin/phpunit
```

It seems it does not find the TestCase class. If I add the phpunit TC class,
it then fails to find the  BrregDataService class being tested.

https://github.com/HelgeSverre/Brreg/blob/master/tests/BrregServiceTest.php#L14

```
Fatal error: Class 'TestCase' not found in /Users/rubendahl/wdir/github/rubendahl/Brreg/tests/BrregServiceTest.php on line 4
```

then after adding `use PHPUnit\Framework\TestCase;` I get:

```
1) BrregServiceTest::it_returns_false_if_the_company_not_found
Error: Class 'App\Services\BrregDataService' not found
```

Tried changing to the full namespace with `use HelgeSverre\Brreg\BrregService as BrregDataService;` but it can't seem to find that either. Seems some of the autoloading magic somewhere is eluding me completely.

Any hints would be appreciated.

**Comment by HelgeSverre** [comment]
This package was a one-off hack, there are no tests, might rebuild this
properly in the future.
