### ISSUE TITLE
Migrating to the new Brreg API end-point.

### ISSUE THREAD

**Issue by kentdahl** [HelgeSverre/Brreg#4]
Seems there is a more updated end-point for the brreg API which some useful changes.

Per my testing so far, the main changes is that "J" and "N" are dropped; we get true / false values directly now. Field names seem to be the same. And the `adresse` field is now an **array**, allowing proper handling of multiple lines for an address (which was why I started digging into this.)

* NEW: https://data.brreg.no/enhetsregisteret/api/enheter/996888460
* OLD: https://data.brreg.no/enhetsregisteret/enhet/996888460.json

API docs: https://data.brreg.no/enhetsregisteret/api/docs/index.html#enheter-oppslag

What would be a good way of moving towards using the new API end-point in future versions?

**Comment by dsbilling** [comment]
This was fixed in 2.0?

**Comment by HelgeSverre** [comment]
Will look through it tomorrow morning

tor. 6. mai 2021, 19:32 skrev Daniel S. Billing ***@***.***>:

**Comment by HelgeSverre** [comment]
Copy paste og bruk dette isteden, fjerner denne pakken ila uken.

```php
<?php

use Illuminate\Support\Facades\Http;


class Brreg
{
    
    public function getByVatId($vatId)
    {
        return Http::get("https://data.brreg.no/enhetsregisteret/api/enheter/$vatId")->json();
    }
    
    public function getRoles($vatId)
    {
        return Http::get("https://data.brreg.no/enhetsregisteret/api/enheter/$vatId/roller")->json();
    }

    public function searchByName($name, $params = [])
    {
        return Http::get("https://data.brreg.no/enhetsregisteret/api/enheter",
            array_merge(["navn" => $name], $params)
        )->json();
    }
}
```
